---
apiVersion: v1
kind: Template
metadata:
  name: module-update-router
labels:
  app: module-update-router
parameters:
  - name: IMAGE
    description: The container image
    value: quay.io/cloudservices/module-update-router
  - name: IMAGE_TAG
    description: The container image tag
    value: latest
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: module-update-router
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: module-update-router
      template:
        metadata:
          labels:
            app: module-update-router
        spec:
          containers:
            - name: module-update-router
              image: ${IMAGE}:${IMAGE_TAG}
              ports:
                - containerPort: 8080
                - containerPort: 2112
  - apiVersion: v1
    kind: Service
    metadata:
      name: module-update-router
    spec:
      selector:
        matchLabels:
          app: module-update-router
      ports:
        - port: 80
          targetPort: 8080
  - apiVersion: v1
    kind: Route
    metadata:
      name: module-update-router
    spec:
      to:
        kind: Service
        name: module-update-router
